// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpcLUpNf3d1NI1AevyYFZOOnWUKI4zwFs',
    appId: '1:624502484704:web:16b90d0b79f2e63eeeea85',
    messagingSenderId: '624502484704',
    projectId: 'fir-task-app-1a835',
    authDomain: 'fir-task-app-1a835.firebaseapp.com',
    storageBucket: 'fir-task-app-1a835.firebasestorage.app',
    measurementId: 'G-RRRZ1KHFG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgshOmOoPJpBTP62h8fxiqbwzTgBGytbQ',
    appId: '1:624502484704:android:a3c3b703d76dbd92eeea85',
    messagingSenderId: '624502484704',
    projectId: 'fir-task-app-1a835',
    storageBucket: 'fir-task-app-1a835.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUyxP8RftnfzS1B2DBCqrWU1-V-1-2CEo',
    appId: '1:624502484704:ios:32de609f63ed8b53eeea85',
    messagingSenderId: '624502484704',
    projectId: 'fir-task-app-1a835',
    storageBucket: 'fir-task-app-1a835.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseMiniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUyxP8RftnfzS1B2DBCqrWU1-V-1-2CEo',
    appId: '1:624502484704:ios:32de609f63ed8b53eeea85',
    messagingSenderId: '624502484704',
    projectId: 'fir-task-app-1a835',
    storageBucket: 'fir-task-app-1a835.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseMiniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpcLUpNf3d1NI1AevyYFZOOnWUKI4zwFs',
    appId: '1:624502484704:web:d365853560c35b9deeea85',
    messagingSenderId: '624502484704',
    projectId: 'fir-task-app-1a835',
    authDomain: 'fir-task-app-1a835.firebaseapp.com',
    storageBucket: 'fir-task-app-1a835.firebasestorage.app',
    measurementId: 'G-TGVLSDYFH7',
  );
}
